apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend
          image: vykhanghuynh/backend-api-k8s:latest

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: DATABASE_URL
            - name: RABBIT_URI
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: RABBIT_URI
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: REDIS_URL
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: backend
spec:
  selector:
    app: backend-api
  ports:
    - port: 8000
  type: ClusterIP
