# k8s/message-service/message-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: vykhanghuynh/message-service
          env:
            - name: RABBIT_URI
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: RABBIT_URI
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: backend
spec:
  selector:
    app: message-service
  ports:
    - port: 3003
  type: ClusterIP
