version: "3.9"

services:
  postgres13:
    image: postgres:13.21-alpine3.21
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nodejs_midterm
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    environment:
      - REDIS_PASSWORD=secret
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=vy@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "5050:80"

volumes:
  data-volume:
  redis-volume:
