apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
  namespace: backend
type: Opaque
stringData:
  DATABASE_URL: "postgresql://root:secret@postgres.data.svc.cluster.local:5432/nodejs_midterm?schema=public"
  RABBIT_URI: "amqp://vy:vy@rabbitmq.data.svc.cluster.local:5672"
  REDIS_URL: "redis://:secret@redis.data.svc.cluster.local:6379"
